VŠE - shrnutí

In [1]:
import numpy as np
import pandas as pd

seznam_list = [1, 2, 3, 4, 5]
seznam_tuple = (1, 2, 3, 4, 5)
seznam_set = {1, 2, 3, 4, 5}
seznam_range = range(1,6)
seznam_np = np.array([1, 2, 3, 4, 5])
seznam_series = pd.Series([1, 2, 3, 4, 5])

In [2]:
print(seznam_list[1]) 
print(seznam_tuple[1]) 
# Set je neuspořádaná množina, vybírat indexem není možné
print(seznam_range[1])
print(seznam_np[1])
print(seznam_series.iat[1])

2
2
2
2
2


In [3]:
print(seznam_list[-1]) 
print(seznam_tuple[-1]) 
# Set je neuspořádaná množina, vybírat indexem není možné
print(seznam_range[-1])
print(seznam_np[-1])
print(seznam_series.iat[-1])

5
5
5
5
5


In [4]:
print(seznam_list + [7, 8])
print(seznam_tuple + (6, 7, 8))

seznam_set.update({7, 8}) # Set neumožňuje duplicitní hodnoty !
print(seznam_set)

#range nelze spojit
print(np.concatenate((seznam_np, np.array([7, 8]))))
print(pd.concat([seznam_series, pd.Series([7,8])], axis=0))

[1, 2, 3, 4, 5, 7, 8]
(1, 2, 3, 4, 5, 6, 7, 8)
{1, 2, 3, 4, 5, 7, 8}
[1 2 3 4 5 7 8]
0    1
1    2
2    3
3    4
4    5
0    7
1    8
dtype: int64


In [5]:
seznam_np = np.array([1, 2, 3, 4, 5])

In [6]:
# Selekce části seznamu s dvěma hranicemi (slicing)
print(seznam_list[1:4])
print(seznam_np[1:4])
print(seznam_tuple[1:4])
# Set neumožňuje slicing
print(seznam_series.iloc[1:4])

[2, 3, 4]
[2 3 4]
(2, 3, 4)
1    2
2    3
3    4
dtype: int64


In [7]:
# Selekce části seznamu s hranicí zprava
print(seznam_list[:3])
print(seznam_tuple[:3])
# Set neumožňuje slicing
print(list(seznam_range[:3]))
print(seznam_np[:3])
print(seznam_series[:3])

[1, 2, 3]
(1, 2, 3)
[1, 2, 3]
[1 2 3]
0    1
1    2
2    3
dtype: int64


In [8]:
# Selekce části seznamu s hranicí zleva
print(seznam_list[2:])
print(seznam_tuple[2:])
# Set neumožňuje slicing
print(list(seznam_range[2:]))
print(seznam_np[2:])
print(seznam_series[2:])

[3, 4, 5]
(3, 4, 5)
[3, 4, 5]
[3 4 5]
2    3
3    4
4    5
dtype: int64


In [9]:
# Krokávání
print(seznam_list[::2])
print(seznam_tuple[::2])
# Set neumožňuje indexování ani krokování, protože je neuspořádaný
print(list(seznam_range[::2]))
print(seznam_np[::2])
print(seznam_series[::2])

[1, 3, 5]
(1, 3, 5)
[1, 3, 5]
[1 3 5]
0    1
2    3
4    5
dtype: int64


In [10]:
# Obrácení seznamu
print(seznam_list[::-1])
print(seznam_tuple[::-1])
# Set neumožňuje indexování ani obrácení, protože je neuspořádaný
print(list(seznam_range[::-1]))
print(seznam_np[::-1]) #alternativa: np.flip(seznam_np)
print(seznam_series[::-1]) 

[5, 4, 3, 2, 1]
(5, 4, 3, 2, 1)
[5, 4, 3, 2, 1]
[5 4 3 2 1]
4    5
3    4
2    3
1    2
0    1
dtype: int64


In [11]:
# Obrácení a ořezání seznamu
print(seznam_list[3:0:-1])
print(seznam_tuple[3:0:-1])
# Set neumožňuje indexování ani obrácení, protože je neuspořádaný
print(list(seznam_range[3:0:-1]))
print(seznam_np[3:0:-1])
print(seznam_series[3:0:-1])

[4, 3, 2]
(4, 3, 2)
[4, 3, 2]
[4 3 2]
3    4
2    3
1    2
dtype: int64


In [12]:
# Získání délky seznamu
print(len(seznam_list))
print(len(seznam_tuple))
print(len(seznam_set))
print(len(seznam_range))
print(len(seznam_np)) #alternativa: np.size(seznam_np)
print(len(seznam_series)) #alternativa: seznam_series.size

5
5
7
5
5
5


In [13]:
seznam_list[0] = 10
print(seznam_list)

# Tuple je neměnný, nelze měnit hodnoty.

#u setu je jedinné možné řešení odstanit a přidat hodnotu
seznam_set.remove(1)
seznam_set.add(10)
print(seznam_set)

# Range nelze upracovat

seznam_np[0] = 10
print(seznam_np)

seznam_series[0] = 10
print(seznam_series)

[10, 2, 3, 4, 5]
{2, 3, 4, 5, 7, 8, 10}
[10  2  3  4  5]
0    10
1     2
2     3
3     4
4     5
dtype: int64


In [14]:
# Přidání nové hodnoty na konec
seznam_list.append(6)
print(seznam_list)

# tuple nelze upravovat

seznam_set.add(6) # Set neumožňuje duplikáty !
print(seznam_set)

# range nelze měnit

seznam_np = np.append(seznam_np, 6)
print(seznam_np)

seznam_series[ len(seznam_series) ] = 6
print(seznam_series)

[10, 2, 3, 4, 5, 6]
{2, 3, 4, 5, 6, 7, 8, 10}
[10  2  3  4  5  6]
0    10
1     2
2     3
3     4
4     5
5     6
dtype: int64


In [15]:
# Zjištění počtu záznamů s určitou hodnotou
print(seznam_list.count(4))
print(seznam_tuple.count(4))
# Set nepodporuje duplicity, tudíž funkce nemá smysl k existenci
# V range nemohou být duplicity
print(np.count_nonzero(seznam_np == 4))
print(seznam_series.value_counts()[4])

1
1
1
1


In [16]:
odstraneny_prvek = seznam_list.pop(0)
print(odstraneny_prvek)     
print(seznam_list)     

#Tuple neobsahuje .pop(), protože je neměnný

odstraneny_prvek = seznam_set.pop()
print(odstraneny_prvek) 
print(seznam_set)

#Range neobsahuje .pop(), protože je neměnný
#NumPy array neobsahuje .pop()

odstraneny_prvek = seznam_series.pop(0)
print(odstraneny_prvek) 
print(seznam_series)

10
[2, 3, 4, 5, 6]
2
{3, 4, 5, 6, 7, 8, 10}
10
1    2
2    3
3    4
4    5
5    6
dtype: int64


NUMPY

In [17]:
#datový typ => uINT8
seznam_np = seznam_np.astype(np.uint8)
new_np_array = np.array([1,2,3,4,5], dtype='uint8')
print(seznam_np.dtype)
print(new_np_array.dtype)

uint8
uint8


In [18]:
#TODO dodělat datové typy

In [19]:
# List
seznam = [1,2,3,4,5,6,7,8,9]
seznam_listX2 = [x * 2 for x in seznam]

#NumPy Array
seznam_np = np.array([1,2,3,4,5,6,7,8,9])
print(seznam_np * 2)
print(seznam_np / 2)
print(seznam_np + 2)
print(seznam_np - 2)

[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[ 3  4  5  6  7  8  9 10 11]
[-1  0  1  2  3  4  5  6  7]


In [20]:
np.set_printoptions(precision=2, suppress=True)

radiány = np.array([0,2,4,6], dtype='float64')
stupně = radiány * (180 / np.pi)
print(stupně)

[  0.   114.59 229.18 343.77]


In [21]:
a = np.array([1,2,1,2])
b = np.array([2,4,2,4])

print(a * b)
print(a / b)
print(a + b)
print(a - b)

[2 8 2 8]
[0.5 0.5 0.5 0.5]
[3 6 3 6]
[-1 -2 -1 -2]


In [22]:
matice = np.array([[1, 2, 3], [2, 4,8]])
matice2 = np.array([1, 2, 3])

print(matice * matice2)

[[ 1  4  9]
 [ 2  8 24]]


In [23]:
#logické operace se seznamy výše
print (matice2 > 2)
print (matice2 < 2)

[False False  True]
[ True False False]


In [24]:
#alternativa k nativnímu range
řada = np.arange(10)
print(řada)

[0 1 2 3 4 5 6 7 8 9]


SERIES

In [25]:
#nahrazení None 'neznámé'
jména = pd.Series(['Jan', 'Anna', 'Petr', 'Tomáš', None, None, 'Marie', 'Pavel'])
jména = jména.fillna('neznámé')
print(jména)

0        Jan
1       Anna
2       Petr
3      Tomáš
4    neznámé
5    neznámé
6      Marie
7      Pavel
dtype: object


In [26]:
#nový seznam bez None
čísla = pd.Series([11, 14, None, 25, None])
čísla = čísla.dropna()
print(čísla)

0    11.0
1    14.0
3    25.0
dtype: float64


In [27]:
#Anglie
import pandas as pd
import csv

path = "England-annual-price-change-by-local-authority-2024-05.csv"
sniffer = csv.Sniffer()
custom_delimiter = sniffer.sniff(open(path).readline().rstrip()).delimiter
df = pd.read_csv(path, delimiter=custom_delimiter)

price_series = df['May 2024']
pd.set_option('display.float_format', '{:.2f}'.format)
print(price_series.describe())

count       317.00
mean     325618.03
std      136019.36
min      106314.00
25%      229841.00
50%      306885.00
75%      390671.00
max     1226545.00
Name: May 2024, dtype: float64


SET

In [28]:
hodnoty = ['a', 'b', 'c', 'a', 'd', 'b']
unikatni_hodnoty = set(hodnoty)
print(unikatni_hodnoty)

{'c', 'd', 'a', 'b'}


In [29]:
byli_v_kině = {'Jan', 'Anna', 'Petr', 'Tomáš'}
byli_v_restauraci = {'Petr', 'Eva', 'Anna', 'Pavel'}

print(byli_v_kině & byli_v_restauraci)  # Průnik
print(byli_v_kině | byli_v_restauraci)  # Sjednocení
print(byli_v_kině - byli_v_restauraci)  # Rozdíl
print(byli_v_kině ^ byli_v_restauraci)  # Symetrický rozdíl

{'Anna', 'Petr'}
{'Anna', 'Tomáš', 'Eva', 'Pavel', 'Jan', 'Petr'}
{'Jan', 'Tomáš'}
{'Tomáš', 'Pavel', 'Jan', 'Eva'}


In [30]:
lidé  = {'Marie', 'Anna', 'Petr', 'Tomáš'}
muži = {'Petr', 'Tomáš'}

print(muži.issubset(lidé)) # Jsou muži podmnožinou lidí?
print(muži.issuperset(lidé)) # Jsou muži nadmnožinou lidí?

True
False
